version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn atomeco.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_NAME: 'atomeco_data_base'
      DB_USER: 'postgres'
      DB_PASSWORD: '123456'
      DB_HOST: 'db'
      DB_PORT: '5432'
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: atomeco_data_base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

volumes:
  postgres_data:
