from waste.project_views.OrganisationView import OrganizationView
from waste.project_views.ConnectionView import ConnectionView
from waste.project_views.RelationsView import RelationsView
from waste.project_views.WasteStorageView import WasteStorageView

